apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: thedevopsguyazurevotingappredis 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thedevopsguyazurevotingappredis 
    spec:
      containers:
        - name: thedevopsguyazurevotingappredis 
          image: jkregistry.azurecr.io/thedevopsguyazurevotingappredis
          ports:
          - containerPort: 80